/* Generated by Yosys 0.37 (git sha1 a5c7f69ed8f, gcc 13.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* top =  1  *)
(* src = "test.v:1.1-11.10" *)
module test(clk, counter);
  (* src = "pla.v:43.8-43.15" *)
  wire _00_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _01_;
  (* src = "pla.v:43.8-43.15" *)
  wire _02_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _03_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _04_;
  (* src = "pla.v:43.8-43.15" *)
  wire _05_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _06_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _07_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _08_;
  (* src = "pla.v:43.8-43.15" *)
  wire _09_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _10_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _11_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _12_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _13_;
  (* src = "pla.v:43.8-43.15" *)
  wire _14_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _15_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _16_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _17_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _18_;
  (* src = "pla.v:58.5-61.4|pla.v:43.8-43.15" *)
  wire _19_;
  (* src = "pla.v:43.8-43.15" *)
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  (* force_downto = 32'd1 *)
  (* src = "test.v:8.13-8.24|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _28_;
  (* src = "test.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "test.v:4.19-4.26" *)
  output [0:7] counter;
  wire [0:7] counter;
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(16'h6142),
    .WIDTH(32'd4)
  ) _29_ (
    .A({ counter[4:5], counter[7], counter[6] }),
    .Y(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(20'h25600),
    .WIDTH(32'd5)
  ) _30_ (
    .A({ _00_, counter[4:5], counter[7], counter[6] }),
    .Y(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(24'h059800),
    .WIDTH(32'd6)
  ) _31_ (
    .A({ _01_, _00_, counter[4:5], counter[7], counter[6] }),
    .Y(_21_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(20'h64120),
    .WIDTH(32'd5)
  ) _32_ (
    .A({ counter[3:5], counter[7], counter[6] }),
    .Y(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(24'h109800),
    .WIDTH(32'd6)
  ) _33_ (
    .A({ _02_, counter[3:5], counter[7], counter[6] }),
    .Y(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(28'h054a000),
    .WIDTH(32'd7)
  ) _34_ (
    .A({ _03_, _02_, counter[3:5], counter[7], counter[6] }),
    .Y(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(32'd39157760),
    .WIDTH(32'd8)
  ) _35_ (
    .A({ _04_, _03_, _02_, counter[3:5], counter[7], counter[6] }),
    .Y(_22_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(24'h640480),
    .WIDTH(32'd6)
  ) _36_ (
    .A({ counter[2:5], counter[7], counter[6] }),
    .Y(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(28'h1026000),
    .WIDTH(32'd7)
  ) _37_ (
    .A({ _05_, counter[2:5], counter[7], counter[6] }),
    .Y(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(32'd68321280),
    .WIDTH(32'd8)
  ) _38_ (
    .A({ _06_, _05_, counter[2:5], counter[7], counter[6] }),
    .Y(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(36'h015820000),
    .WIDTH(32'd9)
  ) _39_ (
    .A({ _07_, _06_, _05_, counter[2:5], counter[7], counter[6] }),
    .Y(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(40'h0095580000),
    .WIDTH(32'd10)
  ) _40_ (
    .A({ _08_, _07_, _06_, _05_, counter[2:5], counter[7], counter[6] }),
    .Y(_23_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(28'h6401200),
    .WIDTH(32'd7)
  ) _41_ (
    .A({ counter[1:5], counter[7], counter[6] }),
    .Y(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(32'd269647872),
    .WIDTH(32'd8)
  ) _42_ (
    .A({ _09_, counter[1:5], counter[7], counter[6] }),
    .Y(_10_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(36'h040260000),
    .WIDTH(32'd9)
  ) _43_ (
    .A({ _10_, _09_, counter[1:5], counter[7], counter[6] }),
    .Y(_11_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(40'h0106080000),
    .WIDTH(32'd10)
  ) _44_ (
    .A({ _11_, _10_, _09_, counter[1:5], counter[7], counter[6] }),
    .Y(_12_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(44'h00560200000),
    .WIDTH(32'd11)
  ) _45_ (
    .A({ _12_, _11_, _10_, _09_, counter[1:5], counter[7], counter[6] }),
    .Y(_13_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(48'h002555800000),
    .WIDTH(32'd12)
  ) _46_ (
    .A({ _13_, _12_, _11_, _10_, _09_, counter[1:5], counter[7], counter[6] }),
    .Y(_24_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(32'd1677740032),
    .WIDTH(32'd8)
  ) _47_ (
    .A({ counter[0:5], counter[7], counter[6] }),
    .Y(_14_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(36'h101820000),
    .WIDTH(32'd9)
  ) _48_ (
    .A({ _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_15_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(40'h0400980000),
    .WIDTH(32'd10)
  ) _49_ (
    .A({ _15_, _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_16_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(44'h01004a00000),
    .WIDTH(32'd11)
  ) _50_ (
    .A({ _16_, _15_, _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_17_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(48'h004180800000),
    .WIDTH(32'd12)
  ) _51_ (
    .A({ _17_, _16_, _15_, _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_18_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(52'h0015802000000),
    .WIDTH(32'd13)
  ) _52_ (
    .A({ _18_, _17_, _16_, _15_, _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(56'h00095558000000),
    .WIDTH(32'd14)
  ) _53_ (
    .A({ _19_, _18_, _17_, _16_, _15_, _14_, counter[0:5], counter[7], counter[6] }),
    .Y(_25_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(8'h96),
    .WIDTH(32'd2)
  ) _54_ (
    .A({ counter[7], counter[6] }),
    .Y(_26_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:48.5-51.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'sd2),
    .TABLE(12'h958),
    .WIDTH(32'd3)
  ) _55_ (
    .A({ counter[5], counter[7], counter[6] }),
    .Y(_20_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:58.5-61.4|pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd2),
    .TABLE(16'h1680),
    .WIDTH(32'd4)
  ) _56_ (
    .A({ _20_, counter[5], counter[7], counter[6] }),
    .Y(_27_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pla.v:38.3-41.4" *)
  GAL_SOP #(
    .DEPTH(32'd1),
    .TABLE(2'h1),
    .WIDTH(32'd1)
  ) _57_ (
    .A(counter[7]),
    .Y(_28_[0])
  );
  (* src = "test.v:7.1-9.4" *)
  DFF_P _58_ (
    .C(clk),
    .D(_28_[0]),
    .Q(counter[7])
  );
  NDFF_P _59_ (
    .C(clk),
    .D(_26_),
    .Q(counter[6])
  );
  NDFF_P _60_ (
    .C(clk),
    .D(_27_),
    .Q(counter[5])
  );
  NDFF_P _61_ (
    .C(clk),
    .D(_21_),
    .Q(counter[4])
  );
  NDFF_P _62_ (
    .C(clk),
    .D(_22_),
    .Q(counter[3])
  );
  NDFF_P _63_ (
    .C(clk),
    .D(_23_),
    .Q(counter[2])
  );
  NDFF_P _64_ (
    .C(clk),
    .D(_24_),
    .Q(counter[1])
  );
  NDFF_P _65_ (
    .C(clk),
    .D(_25_),
    .Q(counter[0])
  );
endmodule
